site_name: CardNow API

nav:
    - Overview: index.md
    - 'Getting Started':
        - 'How it works': 'index.md'
        - 'Accessing the API': 'index.md'
        - 'Authentication': 'index.md'
        - 'How to Test': 'index.md'
    - 'API Reference': 'api-reference.md'
repo_url: https://github.com/RewardLayer/docs/


# Configuration
theme:
    name: null
    custom_dir: material

    # 404 page
    static_templates:
        - 404.html

    # Don't include MkDocs' JavaScript
    include_search_page: false
    search_index_only: true

    # Default values, taken from mkdocs_theme.yml
    language: en
    features:
        - tabs
        #- instant
    palette:
        scheme: default
        primary: indigo
        accent: indigo
    font:
        text: Roboto
        code: Roboto Mono
    favicon: assets/favicon.png
    icon:
        logo: logo
