site_name: CardNow API

# Navigation
nav:
    - Home: 'index.md'
    - 'API Reference':
          - 'Overview': 'api-reference/api-overview.md'
          - 'Monitoring': 'api-reference/monitoring.md'
          - 'Catalog': 'api-reference/catalog.md'
          - 'Ordering': 'api-reference/ordering.md'
          - 'Models': 'api-reference/models.md'
            
repo_url: https://github.com/RewardLayer/docs/
edit_uri: ""
# Copyright
copyright: Copyright &copy; 2020 - 2021 CardNow

# Configuration
theme:
    name: material
    features:
        - navigation.tabs.sticky
        - toc.integrate
        - navigation.sections

#Plug-ins
plugins:
    - search
      
markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.tabbed
    - toc:
        permalink: true