site_name: CardNow API

# Navigation
nav:
    - Home: index.md
    - Overview: 'overview.md'
    - 'Getting Started':
        - 'How it works': 'index.md'
        - 'Accessing the API': 'index.md'
        - 'Authentication': 'index.md'
        - 'How to Test': 'index.md'
    - 'API Reference': 'api-reference.md'
repo_url: https://github.com/RewardLayer/docs/
edit_uri: ""
# Copyright
copyright: Copyright &copy; 2020 - 2021 CardNow

# Configuration
theme:
    name: material
    custom_dir: src/overrides
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - toc.integrate

#Plug-ins
plugins:
    - search