site_name: CardNow API

# Navigation
nav:
    - Home: 'index.md'
    - 'Getting Started':
        - 'How it works' : 'getting-started/index.md'
        - 'Accessing the API' : 'getting-started/index.md'
        - 'Authentication' : 'getting-started/index.md'
    - 'Testing' :
        - 'How to Test' : 'testing/index.md'
    - 'API Reference':
          - 'Overview': 'api-reference/api-overview.md'
          - 'Monitoring': 'api-reference/monitoring.md'
          - 'Catalog': 'api-reference/catalog.md'
          - 'Ordering': 'api-reference/ordering.md'
          - 'Models': 'api-reference/models.md'
            
repo_url: https://github.com/RewardLayer/docs/
edit_uri: ""
# Copyright
copyright: Copyright &copy; 2020 - 2021 CardNow

# Configuration
theme:
    name: material
    features:
        - navigation.tabs.sticky
        - toc.integrate
        - navigation.sections
        - navigation.expand

#Plug-ins
plugins:
    - search
      
markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.tabbed
    - toc:
        permalink: true