site_name: CardNow API
nav:
    - Overview: index.md
    - 'Getting Started':
        - 'How it works': 'index.md'
        - 'Accessing the API': 'index.md'
        - 'Authentication': 'index.md'
        - 'How to Test': 'index.md'
    - 'API Reference':
        - 'Overview' : 'index.md'
        - 'Catalog' : 'index.md'
        - 'Ordering' : 'index.md'
repo_url: https://github.com/RewardLayer/docs/