site_name: CardNow API

# Navigation
nav:
    - Overview: index.md
    - 'Getting Started':
        - 'How it works': 'index.md'
        - 'Accessing the API': 'index.md'
        - 'Authentication': 'index.md'
        - 'How to Test': 'index.md'
    - 'API Reference': 'api-reference.md'
repo_url: https://github.com/RewardLayer/docs/

# Configuration
theme:
    name: material
    features:
        - navigation.tabs
        - toc.integrate