site_name: CardNow API

# Navigation
nav:
    - Home: 'index.md'
    - API Reference: 'api-reference.md'
repo_url: https://github.com/RewardLayer/docs/
edit_uri: ""
# Copyright
copyright: Copyright &copy; 2020 - 2021 CardNow

# Configuration
theme:
    name: material
    features:
        - navigation.tabs.sticky
        - toc.integrate

#Plug-ins
plugins:
    - search
      
markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.tabbed